name: RSpec
on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: macos-latest
    steps:
      - name: Start PostgreSQL on MacOS
        run: |
          brew services start postgresql
          echo "Check PostgreSQL service is running"
          i=10
          COMMAND='pg_isready'
          while [ $i -gt 0 ]; do
              echo "Check PostgreSQL service status"
              eval $COMMAND && break
              ((i--))
              if [ $i == 0 ]; then
                  echo "PostgreSQL service not ready, all attempts exhausted"
                  exit 1
              fi
              echo "PostgreSQL service not ready, wait 10 more sec, attempts left: $i"
              sleep 10
          done
      - name: Create postgres user
        run: |
          psql --command="CREATE USER postgres PASSWORD 'postgres'" --command="\du" postgres
      - name: Create small_democracy database
        run: |
          createdb --owner=postgres small_democracy
          PGPASSWORD=postgres psql --username=postgres --host=localhost --list small_democracy
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.87.0
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - name: Set up webdriver
        uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
      - name: Run tests
        run: bundle exec rake spec
        env:
          APP_ENV: test
          POSTGRES_DB: small_democracy
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          RACK_ENV: test
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          path: |
            spec/goldens/main/failures
            spec/goldens/poll/failures
          if-no-files-found: ignore
