name: Rubocop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Rubocop
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.87.0
      with:
        ruby-version: 3.0.2
    - name: Install dependencies
      run: bundle install
    - name: Run rubocop
      run: bundle exec rake rubocop
